-- users
INSERT INTO users (name, age) VALUES ("Ana", 23);
INSERT INTO users (name, age) VALUES ("Beth", 31);
INSERT INTO users (name, age) VALUES ("Cedric", 19);
INSERT INTO users (name, age) VALUES ("Denise", 42);
INSERT INTO users (name, age) VALUES ("Ellen", 35);
INSERT INTO users (name, age) VALUES ("Felix", 30);
INSERT INTO users (name, age) VALUES ("Gretchen", 17);
INSERT INTO users (name, age) VALUES ("Hugh", 67);
INSERT INTO users (name, age) VALUES ("Ingrid", 33);
INSERT INTO users (name, age) VALUES ("Jack", 44);
INSERT INTO users (name, age) VALUES ("Kyle", 77);
INSERT INTO users (name, age) VALUES ("Lewis", 00);
INSERT INTO users (name, age) VALUES ("Max", 45);
INSERT INTO users (name, age) VALUES ("Neal", 28);
INSERT INTO users (name, age) VALUES ("Oprah", 30);
INSERT INTO users (name, age) VALUES ("Peter", 52);
INSERT INTO users (name, age) VALUES ("Qunicy", 63);
INSERT INTO users (name, age) VALUES ("Ross", 55);
INSERT INTO users (name, age) VALUES ("Stewart", 54);
INSERT INTO users (name, age) VALUES ("Trey", 34);

-- pledges
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 4, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 5, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 6, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 7, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 9, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 10, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 11, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 12, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 13, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 13, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 13, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 14, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 15, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 15, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 16, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 16, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 17, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 18, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 18, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 19, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 19, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 20, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 20, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1234, 20, 10);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Books for Art", "Education", 1234, 2018-12-01, 2018-12-20);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Calculus Books", "Education", 1600, 2018-11-01, 2018-12-01);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Foldable phone", "Technology", 1200000, 2018-06-01, 2019-01-20);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Spring break trip", "Vacation", 7000, 2018-12-01, 2019-02-28);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Wisdom tooth removal", "Medical", 5000, 2018-07-01, 2018-08-14);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Car for college", "Personal", 30000, 2018-06-01, 2018-08-20);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Open source word processor", "Technology", 150, 2018-05-01, 2018-05-20);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Hamilton play", "Entertainment", 10000000, 2018-12-01, 2018-12-20);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Spring term abroad", "Education", 15000, 2018-09-01, 2018-12-20);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Programming courses", "Education", 15000, 2018-07-16, 2018-10-26);
