INSERT INTO users (id, name, age) VALUES (1, 'Finnebar', 17);
INSERT INTO users (id, name, age) VALUES (2, 'Finnebar', 17);
INSERT INTO users (id, name, age) VALUES (3, 'Finnebar', 17);
INSERT INTO users (id, name, age) VALUES (4, 'Finnebar', 17);
INSERT INTO users (id, name, age) VALUES (5, 'Finnebar', 17);
INSERT INTO users (id, name, age) VALUES (6, 'Finnebar', 17);
INSERT INTO users (id, name, age) VALUES (7, 'Finnebar', 17);
INSERT INTO users (id, name, age) VALUES (8, 'Finnebar', 17);
INSERT INTO users (id, name, age) VALUES (9, 'Finnebar', 17);
INSERT INTO users (id, name, age) VALUES (10, 'Finnebar', 17);
INSERT INTO users (id, name, age) VALUES (11, 'Finnebar', 17);
INSERT INTO users (id, name, age) VALUES (12, 'Finnebar', 17);
INSERT INTO users (id, name, age) VALUES (13, 'Finnebar', 17);
INSERT INTO users (id, name, age) VALUES (14, 'Finnebar', 17);
INSERT INTO users (id, name, age) VALUES (15, 'Finnebar', 17);
INSERT INTO users (id, name, age) VALUES (16, 'Finnebar', 17);
INSERT INTO users (id, name, age) VALUES (17, 'Finnebar', 17);
INSERT INTO users (id, name, age) VALUES (18, 'Finnebar', 17);
INSERT INTO users (id, name, age) VALUES (19, 'Finnebar', 17);
INSERT INTO users (id, name, age) VALUES (20, 'Finnebar', 17);

INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (1, 'Help me buy a guitar', 'music', 500.00, '2013-06-30', '2013-07-30');
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (2, 'Help me buy a guitar', 'music', 500.00, '2013-06-30', '2013-07-30');
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (3, 'Help me buy a guitar', 'music', 500.00, '2013-06-30', '2013-07-30');
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (4, 'Help me buy a guitar', 'music', 500.00, '2013-06-30', '2013-07-30');
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (5, 'Help me buy a guitar', 'music', 500.00, '2013-06-30', '2013-07-30');
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (6, 'Help me buy a guitar', 'music', 500.00, '2013-06-30', '2013-07-30');
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (7, 'Help me buy a guitar', 'music', 500.00, '2013-06-30', '2013-07-30');
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (8, 'Help me buy a guitar', 'music', 500.00, '2013-06-30', '2013-07-30');
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (9, 'Help me buy a guitar', 'music', 500.00, '2013-06-30', '2013-07-30');
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (10, 'Help me buy a guitar', 'music', 500.00, '2013-06-30', '2013-07-30');

INSERT INTO pledges (id, amount, user_id, project_id) VALUES (1, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (2, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (3, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (4, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (5, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (6, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (7, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (8, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (9, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (10, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (11, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (12, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (13, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (14, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (15, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (16, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (17, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (18, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (19, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (20, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (21, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (22, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (23, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (24, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (25, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (26, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (27, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (28, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (29, 10.00, 1, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (30, 10.00, 1, 2);
